replicaCount: 1

image:
  repository: nadavdev/counter-service
  pullPolicy: IfNotPresent
  tag: dev

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: counter-service
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

volumes:
  - name: efs-volume
    persistentVolumeClaim:
      claimName: efs-claim

volumeMounts:
  - name: efs-volume
    mountPath: /app/counter.txt
    subPath: counter.txt

nodeSelector: {}

tolerations: []

affinity: {}


efs:
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-04c766103518e0935


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5