apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-path-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 128Mi
  hostPath:
    path: /opt

  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem