name: CI Counter Service

on:
  push:
    branches:
      - dev
    tags:
      - "v*.*.*"

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      CI: false
      
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            nadavdev/counter-service
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha  

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "counter-service/Dockerfile"
          tags: ${{ steps.meta.outputs.tags }}

      
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Helm Upgrade-Install
        run: |
          
          pwd
          ls -la

          # Depndency cli's
          aws --version 
     



          # helm template restaurants-app ./RestaurantApp/helm/restaurants-app \
          #   -f ./Provision-Infrastructure/modules/DeploymentPrep/prep_deployment.yaml \
          #   --set image.tag="${{ needs.CI.outputs.image_tag }}"

          # helm upgrade --install restaurants-app ./RestaurantApp/helm/restaurants-app \
          #   -f ./Provision-Infrastructure/modules/DeploymentPrep/prep_deployment.yaml \
          #   --set image.tag="${{ needs.CI.outputs.image_tag }}"
              


